# ----
# Site

title: RxJS Quickstart
description: All you need to know and nothing you don't about RxJS.
url: http://rxjsftw.in
google_analytics_key:
permalink: pretty
baseurl: /

collections:
  basics:
    title: Basics
    position: 1
  state:
    title: State
    position: 2

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
